import type { Metadata } from 'next';
import './globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Toaster } from '@/components/ui/toaster';
// import AppProvider from './AppProvider/AppProvider';
import { cookies } from 'next/headers';

config.autoAddCss = false;

export const metadata: Metadata = {
    title: 'Whatsapp 2.0',
    description: 'Generated by Whatsapp',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const cookieStore = cookies();
    // const accessToken = cookieStore.get('accessToken');
    return (
        <html lang="en">
            <body className="h-full">
                {/* <AppProvider inititalaccessToken={accessToken?.value}>{children}</AppProvider> */}
                {children}

                <Toaster />
            </body>
        </html>
    );
}
