import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/Sidebar/Sidebar';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Toaster } from '@/components/ui/toaster';

config.autoAddCss = false;

export const metadata: Metadata = {
    title: 'Whatsapp 2.0',
    description: 'Generated by Whatsapp',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="h-full">
                <div className="flex">
                    <Sidebar />
                    {children}
                </div>
                <Toaster />
            </body>
        </html>
    );
}
